### ISSUE TITLE
white window  when clicking bottom tab `Screenshots` because filename contains '%'

### ISSUE THREAD

**Issue by scil** [A9T9/Kantu#127]
white window
![image](https://github.com/A9T9/RPA/assets/2786775/c89c2c43-61bc-400e-a1ef-4deac4cc3fdd)

# the error

![image](https://github.com/A9T9/RPA/assets/2786775/f1c2c835-bc6e-433a-84bd-bcb7c5bd5172)

the error is from here:

![image](https://github.com/A9T9/RPA/assets/2786775/76d55468-f317-4763-ab84-f018801bd584)

# because `decodeURIComponent('%')`:
1. https://stackoverflow.com/questions/7449588/why-does-decodeuricomponent-lock-up-my-browser
2. https://github.com/vercel/next.js/issues/10080

**Comment by A9T9** [comment]
Thank you for reporting this issue. I confirmed it.

**Comment by A9T9** [comment]
Fixed in V9.1.3
