### ISSUE TITLE
Support preferable target selector for action recording (Not using ID)

### ISSUE THREAD

**Issue by liveinaus** [A9T9/Kantu#132]
Hi,

Firstly, thanks for developing UI.Vision RPA, I found it is very useful for my testing.

I am a developer who is building sites (forms) using Vuejs.

Currently, I think the default targets are using IDs. It is ok for most sites, but for a Vuejs site the IDs are generated, and the IDs are changed from time to time. I can give everything an ID, but I don't want to do so if I don't have to.

My workaround is to manually adjust Target to suit my needs. I wondering if we can have a setting to define a preferable selector (or disable using IDs).

Cheers,
Sam

**Comment by A9T9** [comment]
Please see https://forum.ui.vision/t/any-work-around-constant-changing-div-on-google-input-filed/6682/
